module Saasu
  class ContactListItem < Entity

    elements  "salutation" => :string,
              "givenName" => :string,
              "middleInitials" => :string,
              "familyName" => :string,
              "dateOfBirth" => :date,
              "organisation" => :string, 
              "organisationUid" => :integer, 
              "organisationName" => :string,
              "organisationAbn" => :string,
              "organisationWebsite" => :string,
              "organisationPosition" => :string,
              "contactID" => :string,
              "abn" => :string,
              "websiteUrl" => :string,
              "email_address" => :string,     # really! it's not consistant
              "mainPhone" => :string,
              "homePhone" => :string,
              "fax" => :string,
              "city" => :string,
              "mobilePhone" => :string,
              "otherPhone" => :string,
              "statusUid" => :integer,
              "industryUid" => :integer,
              "street" => :string,
              "state" => :string,
              "country" => :string,
              "otherStreet" => :string,
              "otherCity" => :string,
              "otherState" => :string,
              "otherPostCode" => :string,
              "otherCountry" => :string,
              "postCode" => :string,
              "isActive" => :boolean,
              "acceptDirectDeposit" => :boolean,
              "directDepositAccountName" => :string,
              "acceptCheque" => :boolean,
              "chequePayableTo" => :string,
              "tags" => :string,
              "customField1" => :string,
              "customField2" => :string,
              "twitterID" => :string,
              "skypeID" => :string,
              "linkedInPublicProfile" => :string,
              "autoSendStatement" => :boolean,
              "isPartner" => :boolean,
              "isCustomer" => :boolean,
              "isSupplier" => :boolean,
              "saleTradingTermsType" => :integer,
              "saleTradingTermsPaymentDueInInterval" => :integer,
              "saleTradingTermsPaymentDueInIntervalType" => :integer,
              "purchaseTradingTermsPaymentDueInInterval" => :integer,
              "purchaseTradingTermsPaymentDueInIntervalType" => :integer,
              "defaultSaleDiscount" => :decimal,
              "defaultPurchaseDiscount" => :decimal

  end
end
 

